### ISSUE TITLE
geAvailablepurchase not working with react-native-iap 13.0.2

### ISSUE THREAD

**Issue by sandeep14** [hyochan/react-native-iap#2974]
This is My code
try {
      const result = await RNIap.initConnection();
      console.log('IAP connection', result);

      // Now call getAvailablePurchases

     
      try
      {
      const purchases = await RNIap.getAvailablePurchases();
        console.log('Available purchases', purchases);
      }
      catch(e)
      {
        console.warn('IAP error1', e);
      }
      
     
    } catch (err) {
      console.warn('IAP error', err);
    }

my code stuck on this   const purchases = await RNIap.getAvailablePurchases(); not going further not cache or not prining next console. we found this problem in latest react-native-iap Please resolve it on priority it is critical for my project

**Comment by kajalchanawala** [comment]
I'm also encountering this issue with react-native-iap@13.0.2. The getAvailablePurchases() method does not return any purchases, even though there are existing active subscriptions on the account. I've confirmed that:

Subscriptions are valid and active on the test account.

initConnection() completes successfully before calling getAvailablePurchases().

No errors are thrown, the call just returns an empty array.

This behavior worked correctly in earlier versions (e.g., 12.x). Rolling back to a previous version resolves the issue.

Would appreciate any update or workaround. Happy to provide logs or help test a fix if needed.

**Comment by kajalchanawala** [comment]
The call to RNIap.getAvailablePurchases() hangs and doesn't resolve or reject in the latest version, blocking further execution. This is critical and needs urgent attention.

**Comment by jasmin017** [comment]
@hyochan On Android, both RNIap.getAvailablePurchases() and RNIap.getPurchaseHistory() seem to return no results at all, even after successful purchases. Could you please provide some guidance or take a look at the package ?

**Comment by hyochan** [comment]
Apologies for the inconvenience caused! 🙏 This issue should be fixed by #2975, and I’ll be releasing **v13.0.3** shortly with the fix included. Thanks for your patience!

**Comment by jasmin017** [comment]
Thanks @hyochan

**Comment by preyasptl** [comment]
@jasmin017 Did you found that it is fixed by version 13.0.2? I've tried the latest version, but still getPurchaseHistory() return blank array even after successfull purchase. I'm using getPurchaseHistory() when user wants to restore their purchase.

**Comment by Tiepbm** [comment]
> Apologies for the inconvenience caused! 🙏 This issue should be fixed by [#2975](https://github.com/hyochan/react-native-iap/pull/2975), and I’ll be releasing **v13.0.3** shortly with the fix included. Thanks for your patience!

@hyochan hi, I still get the error when calling getAvailablePurchases returning undefined. I tried calling getSubscriptions before calling getAvailablePurchases but that didn't work either, even though getSubscriptions did return data.
I am using iap 13.0.3
react native 0.74.0
Android version 14
this is my code
`    const {getAvailablePurchases,subscriptions, getSubscriptions} = useIAP();
   const handleGetAvailablePurchases = async () => {
        try {
            const purchases:any = await getAvailablePurchases();
            console.log('purchases: ',purchases)
        } catch (error) {
            console.log(error)
        }
    };
`
