### ISSUE TITLE
Purchase Attempt for an already owned item returns Error Code "Unknown"

### ISSUE THREAD

**Issue by Relax594** [hyochan/react-native-iap#3086]
Trying to subscribe to a sku you already own returns ErrorCode "Unknown" instead of "AlreadyOwned" even though the message is correct.

`{code: 'unknown', message: 'Item is already owned', productId: undefined}`

Works fine for ErrorCode.UserCancelled if the user cancels the subscription process.

Android 15
React Native 0.81
React Native IAP 14.4.38

**Comment by hyochan** [comment]
Should be resolved in `14.4.39` by upgrading openiap versions!

**Comment by Relax594** [comment]
@hyochan not fixed. Its still present on Android.

`{code: 'unknown', message: 'Item is already owned', productId: undefined}`

Android 15
React Native 0.81
React Native IAP 14.4.39
